### ISSUE TITLE
ProPublicaCongressAPI.Contracts nuget package doesn't support .netcore1.1 app

### ISSUE THREAD

**Issue by lafritay** [babelshift/ProPublicaCongressAPI#6]
I'm trying to include the Contracts API in a .netcore1.1 app and I'm getting this complaint from nuget:

`Package ProPublicaCongressAPI.Contracts 1.0.0.10 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package ProPublicaCongressAPI.Contracts 1.0.0.10 supports: net452 (.NETFramework,Version=v4.5.2)`

From looking at the package cache, it looks like it's only producing the windows version of the package:

![image](https://user-images.githubusercontent.com/438824/27735236-7d50a64c-5d6c-11e7-87ea-5813055d526e.png)

Not sure if this is related to the nuget spec or the appveyor settings.

**Comment by babelshift** [comment]
Please try the latest NuGet package. Thanks.
